galaxy_info:
  roles_name: deploy
  description: выкладка микросервисов на Docker кластер
  author: Yuriy
  license: MIT
  min_ansible_version: 2.12.10
  platforms:
    - name: Ubuntu
      versions:
        - all
