Vagrant.configure("2") do |config|
  (1..5).each do |i|
    config.vm.define "server#{i}" do |web|
      web.vm.box = "geerlingguy/ubuntu2004"
      web.vm.network "forwarded_port", id: "ssh", host: 2224 + i, guest: 22
      web.vm.network "public_network"
      web.vm.hostname = "server#{i}"
      web.vm.provider "virtualbox" do |v|
        v.name = "server#{i}"
        v.memory = 1024
        v.cpus = 2
      end

      web.vm.provision "shell" do |s|
        ssh_pub_key_path = File.expand_path("~/.ssh/id_rsa.pub")
        ssh_pub_key = File.read(ssh_pub_key_path).strip
        s.inline = <<-SHELL
          sudo apt-get update -y
          mkdir -p /root/.ssh
          echo #{ssh_pub_key}
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end
    end
  end
end
