Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/home/vagrant/code",
    owner: "www-data", group: "www-data"

  config.vm.network "private_network", ip: "192.168.33.10"
end

